# Generated by Django 4.0.6 on 2023-03-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postlikes',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_likes'),
        ),
    ]
