# Generated by Django 4.0 on 2023-09-01 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('followed_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-followed_date'],
            },
        ),
    ]
