# Generated by Django 4.0 on 2023-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
