# Generated by Django 4.0.6 on 2022-10-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_url',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
