# Generated by Django 4.0.6 on 2022-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_userprofile_bio_userprofile_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_url',
            field=models.FileField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
