# Generated by Django 5.0.6 on 2025-05-04 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_viewed', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_viewed'],
            },
        ),
        migrations.AddConstraint(
            model_name='postviews',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_views'),
        ),
    ]
