# Generated by Django 4.0.6 on 2023-07-06 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_alter_post_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_viewed', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_viewed'],
            },
        ),
        migrations.AddConstraint(
            model_name='postviews',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_views'),
        ),
    ]
