# Generated by Django 4.0.6 on 2023-08-17 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postviews',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_views'),
        ),
    ]
