# Generated by Django 4.0 on 2023-08-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='tokens',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_token'),
        ),
    ]
