# Generated by Django 4.0 on 2023-08-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin_alter_user_bio'),
        ('tokens', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokens',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AddField(
            model_name='tokens',
            name='type',
            field=models.CharField(choices=[('email_verification', 'email_verification'), ('password_reset', 'password_reset')], default='email_verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='tokens',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_token'),
        ),
    ]
