# Generated by Django 4.0.6 on 2023-03-21 23:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_sv_e4fce0_gin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sv',
        ),
        migrations.AddField(
            model_name='user',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='users_user_search__e7b12b_gin'),
        ),
    ]
