# Generated by Django 4.0.6 on 2023-03-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_users_user_sv_e4fce0_gin_remove_user_sv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_search__e7b12b_gin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='search_vector',
        ),
    ]
